/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as DoneazaRouteImport } from './routes/doneaza'
import { Route as EchipaRouteImport } from './routes/echipa'
import { Route as EvenimenteRouteImport } from './routes/evenimente'
import { Route as FilialeRouteImport } from './routes/filiale'
import { Route as MembruRouteImport } from './routes/membru'
import { Route as MisiuneRouteImport } from './routes/misiune'
import { Route as VoluntarRouteImport } from './routes/voluntar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ArticoleIndexRouteImport } from './routes/articole.index'
import { Route as ArticoleSlugRouteImport } from './routes/articole.$slug'
import { Route as ComunicateIndexRouteImport } from './routes/comunicate.index'
import { Route as ComunicateSlugRouteImport } from './routes/comunicate.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin.branches'
import { Route as AuthenticatedAdminDonationsRouteImport } from './routes/_authenticated/admin.donations'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminVolunteersRouteImport } from './routes/_authenticated/admin.volunteers'
import { Route as ApiPublicEuplatescCallbackRouteImport } from './routes/api/public/euplatesc/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneazaRoute = DoneazaRouteImport.update({
  id: '/doneaza',
  path: '/doneaza',
  getParentRoute: () => rootRouteImport,
} as any)
const EchipaRoute = EchipaRouteImport.update({
  id: '/echipa',
  path: '/echipa',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenimenteRoute = EvenimenteRouteImport.update({
  id: '/evenimente',
  path: '/evenimente',
  getParentRoute: () => rootRouteImport,
} as any)
const FilialeRoute = FilialeRouteImport.update({
  id: '/filiale',
  path: '/filiale',
  getParentRoute: () => rootRouteImport,
} as any)
const MembruRoute = MembruRouteImport.update({
  id: '/membru',
  path: '/membru',
  getParentRoute: () => rootRouteImport,
} as any)
const MisiuneRoute = MisiuneRouteImport.update({
  id: '/misiune',
  path: '/misiune',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntarRoute = VoluntarRouteImport.update({
  id: '/voluntar',
  path: '/voluntar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArticoleIndexRoute = ArticoleIndexRouteImport.update({
  id: '/articole/',
  path: '/articole/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticoleSlugRoute = ArticoleSlugRouteImport.update({
  id: '/articole/$slug',
  path: '/articole/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicateIndexRoute = ComunicateIndexRouteImport.update({
  id: '/comunicate/',
  path: '/comunicate/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicateSlugRoute = ComunicateSlugRouteImport.update({
  id: '/comunicate/$slug',
  path: '/comunicate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDonationsRoute =
  AuthenticatedAdminDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVolunteersRoute =
  AuthenticatedAdminVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicEuplatescCallbackRoute =
  ApiPublicEuplatescCallbackRouteImport.update({
    id: '/api/public/euplatesc/callback',
    path: '/api/public/euplatesc/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/doneaza': typeof DoneazaRoute
  '/echipa': typeof EchipaRoute
  '/evenimente': typeof EvenimenteRoute
  '/filiale': typeof FilialeRoute
  '/membru': typeof MembruRoute
  '/misiune': typeof MisiuneRoute
  '/voluntar': typeof VoluntarRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/articole/$slug': typeof ArticoleSlugRoute
  '/comunicate/$slug': typeof ComunicateSlugRoute
  '/articole/': typeof ArticoleIndexRoute
  '/comunicate/': typeof ComunicateIndexRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/euplatesc/callback': typeof ApiPublicEuplatescCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/doneaza': typeof DoneazaRoute
  '/echipa': typeof EchipaRoute
  '/evenimente': typeof EvenimenteRoute
  '/filiale': typeof FilialeRoute
  '/membru': typeof MembruRoute
  '/misiune': typeof MisiuneRoute
  '/voluntar': typeof VoluntarRoute
  '/articole/$slug': typeof ArticoleSlugRoute
  '/comunicate/$slug': typeof ComunicateSlugRoute
  '/articole': typeof ArticoleIndexRoute
  '/comunicate': typeof ComunicateIndexRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/euplatesc/callback': typeof ApiPublicEuplatescCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/doneaza': typeof DoneazaRoute
  '/echipa': typeof EchipaRoute
  '/evenimente': typeof EvenimenteRoute
  '/filiale': typeof FilialeRoute
  '/membru': typeof MembruRoute
  '/misiune': typeof MisiuneRoute
  '/voluntar': typeof VoluntarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/articole/$slug': typeof ArticoleSlugRoute
  '/comunicate/$slug': typeof ComunicateSlugRoute
  '/articole/': typeof ArticoleIndexRoute
  '/comunicate/': typeof ComunicateIndexRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/euplatesc/callback': typeof ApiPublicEuplatescCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/despre'
    | '/doneaza'
    | '/echipa'
    | '/evenimente'
    | '/filiale'
    | '/membru'
    | '/misiune'
    | '/voluntar'
    | '/admin'
    | '/articole/$slug'
    | '/comunicate/$slug'
    | '/articole/'
    | '/comunicate/'
    | '/admin/articles'
    | '/admin/branches'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/members'
    | '/admin/volunteers'
    | '/admin/'
    | '/api/public/euplatesc/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/despre'
    | '/doneaza'
    | '/echipa'
    | '/evenimente'
    | '/filiale'
    | '/membru'
    | '/misiune'
    | '/voluntar'
    | '/articole/$slug'
    | '/comunicate/$slug'
    | '/articole'
    | '/comunicate'
    | '/admin/articles'
    | '/admin/branches'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/members'
    | '/admin/volunteers'
    | '/admin'
    | '/api/public/euplatesc/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/despre'
    | '/doneaza'
    | '/echipa'
    | '/evenimente'
    | '/filiale'
    | '/membru'
    | '/misiune'
    | '/voluntar'
    | '/_authenticated/admin'
    | '/articole/$slug'
    | '/comunicate/$slug'
    | '/articole/'
    | '/comunicate/'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/donations'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/volunteers'
    | '/_authenticated/admin/'
    | '/api/public/euplatesc/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  DoneazaRoute: typeof DoneazaRoute
  EchipaRoute: typeof EchipaRoute
  EvenimenteRoute: typeof EvenimenteRoute
  FilialeRoute: typeof FilialeRoute
  MembruRoute: typeof MembruRoute
  MisiuneRoute: typeof MisiuneRoute
  VoluntarRoute: typeof VoluntarRoute
  ArticoleSlugRoute: typeof ArticoleSlugRoute
  ComunicateSlugRoute: typeof ComunicateSlugRoute
  ArticoleIndexRoute: typeof ArticoleIndexRoute
  ComunicateIndexRoute: typeof ComunicateIndexRoute
  ApiPublicEuplatescCallbackRoute: typeof ApiPublicEuplatescCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doneaza': {
      id: '/doneaza'
      path: '/doneaza'
      fullPath: '/doneaza'
      preLoaderRoute: typeof DoneazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echipa': {
      id: '/echipa'
      path: '/echipa'
      fullPath: '/echipa'
      preLoaderRoute: typeof EchipaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenimente': {
      id: '/evenimente'
      path: '/evenimente'
      fullPath: '/evenimente'
      preLoaderRoute: typeof EvenimenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filiale': {
      id: '/filiale'
      path: '/filiale'
      fullPath: '/filiale'
      preLoaderRoute: typeof FilialeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membru': {
      id: '/membru'
      path: '/membru'
      fullPath: '/membru'
      preLoaderRoute: typeof MembruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misiune': {
      id: '/misiune'
      path: '/misiune'
      fullPath: '/misiune'
      preLoaderRoute: typeof MisiuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntar': {
      id: '/voluntar'
      path: '/voluntar'
      fullPath: '/voluntar'
      preLoaderRoute: typeof VoluntarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/articole/': {
      id: '/articole/'
      path: '/articole'
      fullPath: '/articole/'
      preLoaderRoute: typeof ArticoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articole/$slug': {
      id: '/articole/$slug'
      path: '/articole/$slug'
      fullPath: '/articole/$slug'
      preLoaderRoute: typeof ArticoleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicate/': {
      id: '/comunicate/'
      path: '/comunicate'
      fullPath: '/comunicate/'
      preLoaderRoute: typeof ComunicateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicate/$slug': {
      id: '/comunicate/$slug'
      path: '/comunicate/$slug'
      fullPath: '/comunicate/$slug'
      preLoaderRoute: typeof ComunicateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/donations': {
      id: '/_authenticated/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AuthenticatedAdminDonationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/volunteers': {
      id: '/_authenticated/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AuthenticatedAdminVolunteersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/euplatesc/callback': {
      id: '/api/public/euplatesc/callback'
      path: '/api/public/euplatesc/callback'
      fullPath: '/api/public/euplatesc/callback'
      preLoaderRoute: typeof ApiPublicEuplatescCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminDonationsRoute: typeof AuthenticatedAdminDonationsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminVolunteersRoute: typeof AuthenticatedAdminVolunteersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminDonationsRoute: AuthenticatedAdminDonationsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminVolunteersRoute: AuthenticatedAdminVolunteersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  DoneazaRoute: DoneazaRoute,
  EchipaRoute: EchipaRoute,
  EvenimenteRoute: EvenimenteRoute,
  FilialeRoute: FilialeRoute,
  MembruRoute: MembruRoute,
  MisiuneRoute: MisiuneRoute,
  VoluntarRoute: VoluntarRoute,
  ArticoleSlugRoute: ArticoleSlugRoute,
  ComunicateSlugRoute: ComunicateSlugRoute,
  ArticoleIndexRoute: ArticoleIndexRoute,
  ComunicateIndexRoute: ComunicateIndexRoute,
  ApiPublicEuplatescCallbackRoute: ApiPublicEuplatescCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
